trigger:
- main

pool:
  name: SDE

variables:
  build.ArtifactStagingDirectory: '$(Pipeline.Workspace)/artifacts'

steps:
# Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# Install dependencies
- script: |
    npm ci
  displayName: 'Install dependencies'

# Run type-check, lint, and tests
- script: |
    npm run type-check
    npm run lint
    npm run test
  displayName: 'Run type-check, lint, and tests'

# Build the app
- script: |
    npm run build
  displayName: 'Build the app'

# Copy built files to staging directory
- task: CopyFiles@2
  inputs:
    SourceFolder: 'dist'
    Contents: '**'
    TargetFolder: '$(build.ArtifactStagingDirectory)'
  displayName: 'Copy files to artifact staging directory'

# Publish build artifacts
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(build.ArtifactStagingDirectory)'
    artifact: 'intelrobotics'
  displayName: 'Publish build artifacts'

# Delete existing artifact on IIS server
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $TargetPath = "\\10.130.56.55\E$\safehouse-solutions"
      if (Test-Path $TargetPath) {
        try {
          Remove-Item -Path "$TargetPath\*" -Recurse -Force
          Write-Host "Deleted existing files in $TargetPath"
        } catch {
          Write-Error "Failed to delete files in $TargetPath. Error: $($_.Exception.Message)"
          exit 1
        }
      } else {
        Write-Host "Target directory does not exist or is inaccessible."
      }
      exit 0
  displayName: 'Delete existing artifacts on IIS server'

# Deploy new artifact to IIS server
- task: WindowsMachineFileCopy@2
  inputs:
    SourcePath: '$(Build.ArtifactStagingDirectory)'
    MachineNames: '10.130.56.55'
    AdminUserName: '$(adminUsername)'
    AdminPassword: '$(adminPassword)'
    TargetPath: '\\10.130.56.55\E$\safehouse-solutions'
  displayName: 'Deploy to IIS server'
